### ISSUE TITLE
The slides about "Part 2: Complex and Heterogeneous Graphs" are missed.

### ISSUE THREAD

**Issue by forpaperrebuttal** [graph-mining-tutorial/graph-mining-tutorial.github.io#1]
I am particularly interested in the tutorial. The topic is really great.

However, I cannot get the slides (Part 2: Complex and Heterogeneous Graphs) from the website: https://graph-mining-tutorial.github.io/www2021/#slides. Would you mind uploading the slides?  I would really appreciate it.

**Comment by shobeir** [comment]
Added. Thank you for the interest.
